insight:
  enabled: false

database:
  host: shopscreen-db
  name: shopscreen
  user: shopscreen
  password: tVMhDGDw9DyaMBdFJL4ptruubXhhkepT
  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 20Gi


  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

person:
  port: '3008'

company:
  port: '3009'
 
hostname: test-k8s-api-shopscreen.microsignage.com 