---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-db
  labels:
    app: company-db
    chart: {{ template "company.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-db
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: company-db
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: company-db
          image: postgres:11.1-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/postgres
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources:
{{ toYaml .Values.database.resources | indent 12 }}
    {{- with .Values.database.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.database.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.database.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-pvc